name: base
channels:
  - anaconda
  - conda-forge
dependencies:
  - cartopy=0.20.2
  - conda=4.13.0
  - conda-package-handling=1.8.1
  - dask=2022.6.1
  - dask-core=2022.6.1
  - ffmpeg=5.0.1
  - hdf4=4.2.15
  - hdf5=1.12.1
  - ipykernel=6.15.0
  - ipython=8.4.0
  - ipython_genutils=0.2.0
  - jupyter_client=7.3.4
  - jupyter_core=4.10.0
  - jupyter_server=1.18.0
  - jupyter_telemetry=0.1.0
  - jupyterlab=3.4.2
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.14.0
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - matplotlib-inline=0.1.3
  - netcdf4=1.5.8
  - notebook=6.4.11
  - notebook-shim=0.1.0
  - numpy=1.23.0
  - pandas=1.4.3
  - proj=9.0.1
  - pyproj=3.3.1
  - python=3.10.4
  - python-dateutil=2.8.2
  - requests=2.28.0
  - scikit-image=0.19.2
  - scipy=1.8.1
  - shapely=1.8.2
  - urllib3=1.26.9
  - xarray=0.20.1
  - pip:
    - jupyterhub==2.3.1
    - pyqt5-sip==12.9.0
